rundeck/rundeck-cli

- src/main/java/org/rundeck/client/Rundeck.java
- src/main/java/org/rundeck/client/api/RundeckApi.java
- src/main/java/org/rundeck/client/api/model/DateInfo.java
- src/main/java/org/rundeck/client/api/model/JobItem.java
- src/main/java/org/rundeck/client/api/model/JobRun.java
- src/main/java/org/rundeck/client/api/model/ScheduledJobItem.java
- src/main/java/org/rundeck/client/tool/commands/Jobs.java
- src/main/java/org/rundeck/client/tool/commands/Run.java
- src/main/java/org/rundeck/client/tool/options/RunBaseOptions.java
- src/main/java/org/rundeck/client/util/Client.java
When RUNDECK_URL is using `/api/18`:
* job info endpoint `rd jobs info -i ID`
* job runAtTime  `rd run -i ID -@ <time> -- -opt1 val1 -opt2 val2` 
~~~
-@/--at Run the job at the specified date/time. ISO8601 format (yyyy-MM-dd'T'HH:mm:ss'Z')
~~~
> API v18 support

- src/main/java/org/rundeck/client/api/model/Execution.java
- src/main/java/org/rundeck/client/api/model/JobItem.java
- src/main/java/org/rundeck/client/tool/commands/Executions.java
- src/main/java/org/rundeck/client/tool/commands/Jobs.java
- src/main/java/org/rundeck/client/tool/options/ExecutionOutputFormatOption.java
- src/main/java/org/rundeck/client/tool/options/JobOutputFormatOption.java
- src/main/java/org/rundeck/client/tool/options/VerboseOption.java
- src/main/java/org/rundeck/client/util/Format.java
- src/test/groovy/org/rundeck/client/util/FormatSpec.groovy
* simplified default format for execution/job listing
* add `-%/--outformat` flag for execution/job listing, specifying
output format in the form "%id %name" etc.  When used, only the data
while be echoed
* add `-v/--verbose` to job/execution list, showing all data fields
> Formatting improvements:

- src/main/java/org/rundeck/client/api/RundeckApi.java
- src/main/java/org/rundeck/client/tool/commands/Jobs.java
- src/main/java/org/rundeck/client/tool/commands/Run.java
- src/main/java/org/rundeck/client/tool/options/JobListOptions.java
- src/test/groovy/org/rundeck/client/tool/commands/JobsSpec.groovy
- src/test/groovy/org/rundeck/client/tool/commands/RunSpec.groovy
Add jobxact/groupxact options for job list/purge
fix #45
> Use exact job name/group query for `job run -j`

- build.gradle
- docs/configuration.md
> Support unix config file at ~/.rd/rd.conf

- docs/commands.md
The `-y` or `--confirm` flags were not in the github.io documentation, but were found in the source code (and generated `--help` output).
> adds confirmation option to execution command (and subcommands)

- src/main/java/org/rundeck/client/api/model/DateInfo.java
- src/main/java/org/rundeck/client/tool/Main.java
- src/main/java/org/rundeck/client/tool/options/RunBaseOptions.java
- src/test/groovy/org/rundeck/client/api/model/DateInfoSpec.groovy
> Fix execution datetime parse issue

- src/main/java/org/rundeck/client/util/Format.java
- src/test/groovy/org/rundeck/client/util/FormatSpec.groovy
If the output of a command contains the chars "$" or "\" and the
formatter is used, the characters "$" and "\" are not handled. Hence,
an exception is thrown:
java.lang.IllegalArgumentException: Illegal group reference
at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
at org.rundeck.client.util.Format.format(Format.java:44)
1. Create a job "mytestjob", which executes the inline script `echo '$some-test$'`
2. Execute the job via cli command: `rd run --outformat '%node: %log' --job 'mytestjob' --follow`
> java.lang.IllegalArgumentException: Illegal group reference
at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
at org.rundeck.client.util.Format.format(Format.java:44)
no exception, just the output:
> $some-test$
> Handle chars "$" and "\" in job output if formatter is used

- src/main/java/org/rundeck/client/api/model/ScmActionInputsResult.java
- src/main/java/org/rundeck/client/api/model/ScmExportItem.java
- src/main/java/org/rundeck/client/api/model/ScmImportItem.java
- src/main/java/org/rundeck/client/api/model/ScmInputField.java
- src/main/java/org/rundeck/client/api/model/ScmSetupInputsResult.java
- src/main/java/org/rundeck/client/tool/commands/projects/SCM.java
- src/test/groovy/org/rundeck/client/tool/commands/projects/SCMSpec.groovy
Updates `projects scm perform` to allow including items automatically, instead of requiring them to be specified manually.
flags for export: 
* `-A/--allitems` includes all changes (modified or deleted jobs)
* `-M/--allmodified` includes all modified jobs
* `-D/--alldeleted` includes deleted jobs
flags for import: 
* `-A/--allitems` includes all files (tracked and untracked)
* `-T/--alltracked` includes all "tracked" files (matching already imported jobs)
* `-U/--alluntracked` includes all "untracked" files (not matching existing jobs)
Using these flags will query for items from the `inputs` response, and adds all items to the action automatically that match the criteria.
Examples
Commit all modified jobs: `rd projects scm perform -a project-commit -i export -p MyProject -f 'message=My …
> Fix #62 add flags to scm perform to include items automatically

- docs/scripting.md
- docs/ssl.md
Replaced RUNDECK_URL, RUNDECK_TOKEN, and DATE_FORMAT with RD_* equivalents across documentation files.
> Keep environment variables consistent across documentation

- docs/install.md
I made and have been maintaining a [simple Arch package in the Arch User Repositories (AUR)](https://aur.archlinux.org/packages/rundeck-cli). Might be nice to get it in the install docs :)
Also fixed the anchors for rpm/debian sections, as they weren't working before.
> Add install docs for Arch Linux

- rd-api-client/src/main/java/org/rundeck/client/RundeckClient.java
- rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/metrics/EndpointListResult.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/metrics/HealthCheckStatus.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/metrics/MetricsData.java
- src/main/java/org/rundeck/client/tool/Main.java
- src/main/java/org/rundeck/client/tool/commands/Metrics.java
- src/test/groovy/org/rundeck/client/tool/commands/MetricsSpec.groovy
- src/test/groovy/org/rundeck/client/tool/commands/SchedulerSpec.groovy
* updates default api version to 25
* new 'metrics' command and subcommands:
rd metrics data        - Prints the metrics data
rd metrics healthcheck - Print health check status information
rd metrics list        - Print system information and stats
rd metrics ping        - Returns a simple response
rd metrics threads     - Print system threads status information
> CLI metrics commands

- CHANGELOG.md
- rd-api-client/src/main/java/org/rundeck/client/RundeckClient.java
- rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/executions/MetricsResponse.java
- rd-api-client/src/main/java/org/rundeck/client/util/Format.java
- src/main/java/org/rundeck/client/tool/commands/Adhoc.java
- src/main/java/org/rundeck/client/tool/commands/Executions.java
- src/main/java/org/rundeck/client/tool/options/ExecutionResultOptions.java
- src/main/java/org/rundeck/client/tool/options/QueryOptions.java
Adds new command 'rd executions metrics help'
> support for execution metrics API

- docs/commands.md
from changes introduced on #206 
* get execution state (rd executions state)
* delete all job executions (rd executions deleteall)
* toggle job execution (rd jobs enablebulk and disablebulk)
* toggle job schedule (rd jobs reschedulebulk and unschedulebulk)
* server cluster scheduler takeover (rd scheduler takeover)
Fix #205
> Fix missing documentation 

- rd-api-client/src/main/java/org/rundeck/client/RundeckClient.java
- src/main/java/org/rundeck/client/tool/Main.java
to suppress warnings about insecure ssl
Before this patch, when you use a self-signed ssl cert in a rundeck setup, rd tools will always present the line:
This change will suppress such warnings if you add the line
export RD_INSECURE_SSL_NO_WARN=true
in ~/.rd/rd.conf file.
> added env var RD_INSECURE_SSL_NO_WARN handling

- build.gradle
- rd-api-client/build.gradle
fixes #217 
This may resolve the issue a user is facing with supported cipher suites. This version of OKHTTP appears to have the necessary cipher suite in the approved list: https://github.com/square/okhttp/blob/parent-3.5.0/okhttp/src/main/java/okhttp3/ConnectionSpec.java#L49 .
> Upgrade OKHTTP to a version that includes sha384

- .travis.yml
- dockers/install/upgrade-rpm/Dockerfile
- rd-cli-tool/build.gradle
- scripts/rpm-upgrade.sh
fix #242 
the /usr/bin/rd symlink is not removed on uninstall, causing upgrade to fail.
> Fix #242 overwrite symlink if present, and remove on uninstall, add tests

- docs/commands.md
- rd-cli-tool/src/main/java/org/rundeck/client/tool/options/FollowOptions.java
The previous help text for `rd run --quiet` implied that using -q option alone would make the command wait until completion, which is incorrect.
(merge of https://github.com/rundeck/rundeck-cli/pull/259)
---
The previous help text for rd run --quiet implied that using -q option alone would make the command wait until completion, which is incorrect.
Fixes #258
> Update help text of rd run --quiet for clarity

- rd-cli-tool/build.gradle
Adds [rd-ext-acl](https://github.com/rundeck/rd-ext-acl/) extension as a bundled jar, which provides the `rd acl (create|list|test|validate)` subcommands for ACL policy files.
> adds rd-ext-acl extension

- rd-cli-tool/src/main/java/org/rundeck/client/tool/Main.java
fix #323 using array char similar to yaml:
```
- id: 4ed0ea80-cc42-4ace-b905-9f7ebd828a92
name: child
project: test3
href: http://outatime.local:4440/api/35/job/4ed0ea80-cc42-4ace-b905-9f7ebd828a92
permalink: http://outatime.local:4440/project/test3/job/show/4ed0ea80-cc42-4ace-b905-9f7ebd828a92
description: 
- id: 31185ae0-f822-4749-b764-78950c6c323c
name: parent
project: test3
href: http://outatime.local:4440/api/35/job/31185ae0-f822-4749-b764-78950c6c323c
permalink: http://outatime.local:4440/project/test3/job/show/31185ae0-f822-4749-b764-78950c6c323c
description: 
```
> Fix #323 indentation in verbose data output

- docs/configuration.md
- rd-api-client/src/main/java/org/rundeck/client/RundeckClient.java
enable config for READ,CONN,WRITE,CALL timeouts individually
using RD_HTTP_*_TIMEOUT env vars, where RD_HTTP_TIMEOUT will
set READ,WRITE,CONN to the same value.
> fix #262 increase default read/connect timeouts (10m/2m)

- rd-cli-tool/src/main/java/org/rundeck/client/tool/Main.java
This reverts commit 92f399636c8b5474854da9b669d7ce171ea6b2ee.
Fix #332
> Revert "Fix #323 indentation in verbose data output"

- rd-api-client/src/main/java/org/rundeck/client/util/ConfigBase.java
- rd-api-client/src/main/java/org/rundeck/client/util/ConfigSource.java
- rd-api-client/src/main/java/org/rundeck/client/util/ConfigValues.java
- rd-api-client/src/main/java/org/rundeck/client/util/Env.java
- rd-api-client/src/main/java/org/rundeck/client/util/ExtConfigSource.java
- rd-api-client/src/main/java/org/rundeck/client/util/MapConfigValues.java
- rd-api-client/src/main/java/org/rundeck/client/util/MultiConfigSource.java
- rd-api-client/src/main/java/org/rundeck/client/util/MultiConfigValues.java
- rd-api-client/src/main/java/org/rundeck/client/util/SysProps.java
- rd-api-client/src/test/groovy/org/rundeck/client/util/EnvSpec.groovy
- rd-api-client/src/test/groovy/org/rundeck/client/util/MultiConfigValuesSpec.groovy
- rd-api-client/src/test/groovy/org/rundeck/client/util/SysPropsSpec.groovy
- rd-cli-tool/build.gradle
- rd-cli-tool/src/main/java/org/rundeck/client/tool/Main.java
> Enable extensions in shadow build

- rd-cli-tool/build.gradle
quell warnings caused by Retrofit 2.8
https://github.com/square/retrofit/issues/3341
> Fix #331 java 11 illegal access warnings

- rd-api-client/src/main/java/org/rundeck/client/util/Format.java
- rd-cli-tool/src/test/groovy/org/rundeck/client/util/FormatSpec.groovy
* support `_-` chars in output format key names
fixes #352 
* note: I originally added support for `:` char as well, however it broke a testcase like `%id:%token`. I think adding `:` makes sense in the node output case because node attributes do use `:` char, but we need to add another syntax that would allow the `%id:%token` to still work, something like `${id}:${token}` or `%{id}:%{token}` with a suffix in the syntax. I am not addressing that in this bug fix, it will have to be a future enhancement.
> Fix #352 node attribute expansion not working for ssh-xyz attributes

- rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java
- rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/projects/Archives.java
A couple of new arguments supported by API 34 and later are not exposed in the CLI causing incomplete import during DR practice.
Adding everything till API 38.
Ref: https://docs.rundeck.com/docs/api/rundeck-api.html#project-archive-import
> Fix: Add arguments for project import till API 38

- rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Run.java
- rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/RunSpec.groovy
picocli requires integer return value to indicate exit code, boolean is not sufficient.
> RUN-993: Fix #446 exit code should not be 0 when run -f execution fails

- rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java
- rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/projects/Archives.java
- rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/projects/ArchivesSpec.groovy
Specify enabled components with `--component name` or `-I name` (allows multiple)
Specify options for components with `--options name.key=value` or `-O`
> RUN-1348: Add component options to project archives import

- rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/projects/Archives.java
Use correct name for project tours import component, and link to API docs.
Note: API docs PR to fix project tours import component name is here: https://github.com/rundeck/docs/pull/1174
> RUN-1490: Correct suggested import component

- rd-cli-tool/build.gradle
Removes warning message when running on java11. Previous fix was not running and "JAVACMD" variable was out of the scope.
> RSE-329: jdk11-warning

- CHANGELOG.md
- rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/ImportResult.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/JobFileItem.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/JobItem.java
- rd-api-client/src/main/java/org/rundeck/client/api/model/JobLoadItem.java
- rd-api-client/src/test/groovy/org/rundeck/client/api/model/ImportResultSpec.groovy
- rd-api-client/src/test/groovy/org/rundeck/client/api/model/JobLoadItemSpec.groovy
- rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Executions.java
Note: XML support has been deprecated in Rundeck API since version 4.0.0
> remove use of XML in api responses. remove --xml option for execution metrics

- rd-api-client/src/main/java/org/rundeck/client/RundeckClient.java
- rd-cli-tool/src/test/groovy/org/rundeck/client/RundeckClientSpec.groovy
> fix #465: user+pass auth url incorrect if API version specified in URL

- gradle/libs.versions.toml
> RUN-2025: upgrade rundeck core 4.17.3

- rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java
- rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Jobs.java
- rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/JobsSpec.groovy
the `format` URL parameter in job load API request overrides the Accept header to define the response content type.
Remove the parameter and let the Accept header determine response format.
> RUN-2080: fix #538 format parameter overrides content type

- rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java
- rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/projects/Archives.java
- rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/projects/ArchivesSpec.groovy
Problem: When exporting a project and then importing into another instance, the Project Import feature fails to import webhooks if they already exist in the current project. Consequently, the webhook definitions are not updated.
Expected Outcome: Rundeck should treat webhook as it treats jobs when imported. 
Proposed Solution: If a Webhook is being imported and should update an existing Webhook use the same UUID when saving the updated Webhook, this small change allows Webhooks to be updated when exported and imported over itself. Also, a new option should be added when importing a project to allow users to keep the same webhook UUID or generate new ones. By making these changes the Webhooks would be handled in the same way jobs are handled when a Project is imported over itself. 
Related …
> RSE-955 FIX: Allow update existing webhooks at project import

- .circleci/config.yml
This PR will enable Snyk Open Source scans in CircleCI.  
Changes Include:
1. Updating the CircleCI config.yml to add the Snyk orb, and adding a job to run that scan
Please update as needed and merge these PRs when you feel comfortable to do so. 
We are asking the teams that own each repository to carefully test and merge these changes so they can monitor for any resulting issues, as they are more familiar with the code and deploy process.
> RUN-3091: Add Snyk to CircleCI pipeline

- .github/workflows/release.yml
- CHANGELOG.md
- docs/_config.yml
- docs/changes.md
Sets the ubuntu version to 22.04 so github release action is able to install dpkg-sig
> RRUN-3329: specify ubuntu
