src/main/java/org/rundeck/client/tool/commands/Keys.java
=> Fix #9 for create/upload password, read first line of file

src/main/java/org/rundeck/client/tool/commands/Keys.java
=> fix #14 require path input for rd keys

build.gradle, src/main/java/org/rundeck/client/tool/App.java, src/main/java/org/rundeck/client/tool/commands/Adhoc.java, src/main/java/org/rundeck/client/tool/commands/Executions.java, src/main/java/org/rundeck/client/tool/commands/Jobs.java, src/main/java/org/rundeck/client/tool/commands/Keys.java, src/main/java/org/rundeck/client/tool/commands/Projects.java, src/main/java/org/rundeck/client/tool/commands/Run.java, src/main/java/org/rundeck/client/tool/commands/projects/ACLs.java, src/main/java/org/rundeck/client/tool/commands/projects/Readme.java, src/main/java/org/rundeck/client/tool/commands/system/ACLs.java
=> Don't show stacktrace for input error

docs/commands.md, src/main/java/org/rundeck/client/api/RundeckApi.java, src/main/java/org/rundeck/client/api/model/ScmActionInputsResult.java, src/main/java/org/rundeck/client/api/model/ScmActionPerform.java, src/main/java/org/rundeck/client/api/model/ScmExportItem.java, src/main/java/org/rundeck/client/api/model/ScmImportItem.java, src/main/java/org/rundeck/client/api/model/ScmInputField.java, src/main/java/org/rundeck/client/api/model/ScmJobItem.java, src/main/java/org/rundeck/client/api/model/ScmPlugin.java, src/main/java/org/rundeck/client/api/model/ScmPluginsResult.java, src/main/java/org/rundeck/client/api/model/ScmProjectStatusResult.java, src/main/java/org/rundeck/client/api/model/ScmSetupInputsResult.java, src/main/java/org/rundeck/client/api/model/ScmSynchState.java, src/main/java/org/rundeck/client/tool/commands/ApiCommand.java, src/main/java/org/rundeck/client/tool/commands/Projects.java, src/main/java/org/rundeck/client/tool/commands/projects/SCM.java, src/main/java/org/rundeck/client/tool/options/OptionUtil.java
Add SCM commands:
disable     - Disable plugin
enable      - Enable plugin
inputs      - Get SCM action inputs
perform     - Perform SCM action
plugins     - List SCM plugins
setupinputs - Get SCM Setup inputs
status      - Get SCM Status for a Project
fix #44
=> Add SCM commands

src/main/java/org/rundeck/client/api/model/ScheduledJobItem.java, src/main/java/org/rundeck/client/tool/options/JobOutputFormatOption.java, src/main/java/org/rundeck/client/util/Format.java, src/test/groovy/org/rundeck/client/tool/commands/JobsSpec.groovy, src/test/groovy/org/rundeck/client/util/FormatSpec.groovy
=> Fix jobs info --outformat

build.gradle
* Modify shadow start script as well as normal start script
* Verify changes present in generated scripts during check phase of build.
=> Fix #60 add conf file sourcing in shadow rd script

docs/configuration.md, docs/ssl.md, src/main/java/org/rundeck/client/Rundeck.java, src/main/java/org/rundeck/client/tool/Main.java
=> Add RD_INSECURE_SSL=true to disable SSL cert/hostname checks

docs/commands.md, src/main/java/org/rundeck/client/api/RundeckApi.java, src/main/java/org/rundeck/client/api/model/ProjectExportStatus.java, src/main/java/org/rundeck/client/api/model/ProjectImportStatus.java, src/main/java/org/rundeck/client/tool/commands/Projects.java, src/main/java/org/rundeck/client/tool/commands/projects/Archives.java, src/main/java/org/rundeck/client/tool/options/ProjectNameOptions.java, src/main/java/org/rundeck/client/tool/options/ProjectRequiredNameOptions.java, src/main/java/org/rundeck/client/util/Client.java
`rd projects archives export/import`
API v18 or earlier uses synchronous export, 19+ uses async
=> Add project archive import/export

build.gradle, src/main/java/org/rundeck/client/api/model/DateInfo.java, src/test/groovy/org/rundeck/client/tool/commands/ExecutionsSpec.groovy
=> Fix broken run command

CHANGELOG.md, build.gradle, docs/commands.md, src/main/java/org/rundeck/client/api/RundeckApi.java, src/main/java/org/rundeck/client/api/model/ApiToken.java, src/main/java/org/rundeck/client/api/model/CreateToken.java, src/main/java/org/rundeck/client/api/model/DateInfo.java, src/main/java/org/rundeck/client/tool/commands/Tokens.java, src/test/groovy/org/rundeck/client/tool/commands/TokensSpec.groovy
Also add api v19 support for rd tokens
=> Handle buggy create token response fix #95

build.gradle, docs/commands.md, src/main/java/org/rundeck/client/api/RundeckApi.java, src/main/java/org/rundeck/client/api/model/ExecutionMode.java, src/main/java/org/rundeck/client/api/model/SystemMode.java, src/main/java/org/rundeck/client/tool/commands/RDSystem.java, src/main/java/org/rundeck/client/tool/commands/system/Mode.java
=> Add execution mode control to rd system

src/main/java/org/rundeck/client/api/LoginFailed.java, src/main/java/org/rundeck/client/util/FormAuthInterceptor.java, src/test/groovy/org/rundeck/client/util/FormAuthInterceptorSpec.groovy
=> Improve username/password auth flow

src/main/java/org/rundeck/client/tool/commands/Adhoc.java, src/main/java/org/rundeck/client/tool/commands/AppCommand.java, src/main/java/org/rundeck/client/tool/commands/Executions.java, src/main/java/org/rundeck/client/tool/commands/Jobs.java, src/main/java/org/rundeck/client/tool/commands/Run.java, src/main/java/org/rundeck/client/tool/commands/projects/ACLs.java, src/main/java/org/rundeck/client/tool/commands/projects/SCM.java, src/main/java/org/rundeck/client/tool/commands/system/ACLs.java, src/main/java/org/rundeck/client/util/Client.java, src/main/java/org/rundeck/client/util/ServiceClient.java, src/test/groovy/org/rundeck/client/tool/commands/ExecutionsSpec.groovy
* adhoc
* executions follow
* run
* jobs list
* project/system acls upload/create
* project scm setup/perform
=> fix #128 api calls not auto downgrading

.travis.yml, build.gradle, dockers/install/debian/Dockerfile, scripts/deb-install.sh
=> Fix deb script issue

src/main/java/org/rundeck/client/api/RundeckApi.java, src/main/java/org/rundeck/client/api/model/ExecRetry.java, src/main/java/org/rundeck/client/tool/Main.java, src/main/java/org/rundeck/client/tool/commands/Retry.java, src/main/java/org/rundeck/client/tool/options/RetryBaseOptions.java, src/main/java/org/rundeck/client/tool/options/RetryExecutionOption.java, src/test/groovy/org/rundeck/client/tool/commands/RetrySpec.groovy
CLI call to the new endpoint:
`POST /api/23/job/[ID]/retry/[EXECID]`
Depends on rundeck/rundeck#3372
=> Run execution with just failed nodes

src/main/java/org/rundeck/client/api/model/KeyStorageItem.java, src/main/java/org/rundeck/client/tool/commands/Keys.java, src/test/groovy/org/rundeck/client/tool/commands/KeysSpec.groovy
Fix NPE on Keys list on two cases:
* No path is specified
* No keys are present on the server (#177)
=> Fix for Keys list

rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java, src/main/java/org/rundeck/client/tool/commands/projects/Archives.java
for rundeck/rundeck#4273
`include-scm` to `projects archive import` and `scm` to  `projects archive export`
=> Export and Import SCM project settings

rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java, rd-api-client/src/main/java/org/rundeck/client/api/model/RoleList.java, src/main/java/org/rundeck/client/tool/commands/Users.java, src/test/groovy/org/rundeck/client/tool/commands/UsersSpec.groovy
CLI for https://github.com/rundeck/rundeck/pull/4441
=> List the roles for the authenticated user.

src/main/java/org/rundeck/client/tool/Main.java
Enable plugin command by default.
=> Enable plugin command by default.

rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java, rd-api-client/src/main/java/org/rundeck/client/api/model/repository/Artifact.java, src/main/java/org/rundeck/client/tool/commands/repository/InstallPlugin.java, src/main/java/org/rundeck/client/tool/commands/repository/Plugins.java, src/main/java/org/rundeck/client/tool/commands/repository/RepositoryResponseHandler.java, src/main/java/org/rundeck/client/tool/commands/repository/UninstallPlugin.java, src/main/java/org/rundeck/client/tool/commands/repository/UploadPlugin.java, src/test/groovy/org/rundeck/client/tool/commands/repository/InstallPluginTest.groovy, src/test/groovy/org/rundeck/client/tool/commands/repository/UploadPluginTest.groovy
Enhance the plugin list output.
Add the ability to specify repositories for install and upload.
=> Enhance plugin commands

rd-api-client/build.gradle, rd-api-client/src/main/java/org/rundeck/client/RundeckClient.java, rd-cli-tool/build.gradle, rd-cli-tool/src/main/java/org/rundeck/client/tool/Main.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Version.java
`rd version` prints version info, `rd version -v` prints extended information
=> Version command

rd-api-client/build.gradle, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/AppCommandSpec.groovy, rd-cli-tool/src/test/groovy/org/rundeck/client/util/FormAuthInterceptorSpec.groovy
=> Update retrofit and jackson

docs/commands.md, rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Adhoc.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/AdhocBaseOptions.java, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/AdhocSpec.groovy
=> Fix #276 add script interpreter, file extension, quoted args options to adhoc

.github/workflows/gradle.yml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, rd-api-client/build.gradle, rd-cli-base/build.gradle, rd-cli-lib/build.gradle, rd-cli-tool/build.gradle, rd-cli-tool/src/main/java/org/rundeck/client/tool/Main.java, scripts/deb-install.sh, scripts/rpm-install.sh, scripts/rpm-upgrade.sh
=> Upgrade to gradle 6.2.1

rd-api-client/src/main/java/org/rundeck/client/api/RundeckApi.java, rd-api-client/src/main/java/org/rundeck/client/api/model/BulkJobDelete.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Jobs.java, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/JobsSpec.groovy
* use json content to POST id list
* add batch size and max size options for purge command
=> Fix #295 URI too large error for jobs bulk delete

gradle.properties, rd-api-client/build.gradle, rd-cli-base/build.gradle, rd-cli-tool/build.gradle, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/JobsSpec.groovy
=> Update retrofit, snakeyaml dependencies

docs/extensions.md, rd-api-client/build.gradle, rd-api-client/src/main/java/org/rundeck/client/RundeckClient.java, rd-api-client/src/main/java/org/rundeck/client/api/model/ErrorResponse.java, rd-api-client/src/main/java/org/rundeck/client/api/model/ExecutionStateResponse.java, rd-api-client/src/main/java/org/rundeck/client/api/model/ImportResult.java, rd-api-client/src/main/java/org/rundeck/client/api/model/JobFileItem.java, rd-api-client/src/main/java/org/rundeck/client/api/model/JobItem.java, rd-api-client/src/main/java/org/rundeck/client/api/model/JobLoadItem.java, rd-api-client/src/test/groovy/org/rundeck/client/api/model/ErrorResponseSpec.groovy, rd-api-client/src/test/groovy/org/rundeck/client/api/model/ImportResultSpec.groovy, rd-api-client/src/test/groovy/org/rundeck/client/api/model/JobLoadItemSpec.groovy, rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/projects/ACLs.java
=> Change xml parser to jaxb from simplexml

rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Executions.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Run.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/AdhocBaseOptions.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/ExecutionOutputFormatOption.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/ExecutionsFollowOptions.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/FollowOptions.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/OutputFormat.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/RetryBaseOptions.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/RunBaseOptions.java, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/RunSpec.groovy
=> Fix #285 rd run output supports -v and -% and RD_FORMAT when not using follow mode

rd-api-client/src/main/java/org/rundeck/client/api/model/ScmActionPerform.java, rd-api-client/src/main/java/org/rundeck/client/api/model/ScmImportItem.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/projects/SCM.java, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/projects/SCMSpec.groovy
extends https://github.com/rundeck/rundeck-cli/pull/327
=> Fix #305 scm perform for import should include deletedJobs in request

build.gradle, rd-cli-tool/src/main/java/org/rundeck/client/tool/Main.java, rd-cli-tool/src/main/resources/rd-banner.txt
use runtime version info instead of build time
=> fix: snapshot build version is not shown in banner

dockers/install/rpm/Dockerfile, dockers/install/upgrade-rpm/Dockerfile, scripts/install-test.sh
=> Fix Centos install test

rd-api-client/build.gradle, rd-cli-base/build.gradle, rd-cli-tool/build.gradle
Tests seem to be working be fine. Following up #355
=> OkHttp dependency upgrade

rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/projects/Archives.java
PR moved from https://github.com/rundeck/rundeck-cli/pull/473
=> RUN-1146 Add --file to ensure backward compatibility

.github/workflows/release.yml, .github/workflows/test-signing.yml, .gitmodules, scripts/sign-packages.sh
https://github.com/rundeck/packaging/pull/39
=> update signing script usage due to packaging repo update

rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Run.java, rd-cli-tool/src/main/java/org/rundeck/client/tool/options/RunBaseOptions.java, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/RunSpec.groovy
=> RUN-1580: Fix run --at parsing

rd-cli-tool/src/main/java/org/rundeck/client/tool/commands/Executions.java, rd-cli-tool/src/test/groovy/org/rundeck/client/tool/commands/ExecutionsSpec.groovy
=> RUN-1631: fix exit code for executions deletebulk --require

.github/workflows/release.yml
Change github release to use the `gh` tool
=> use gh release

.github/workflows/gradle.yml, .github/workflows/test-signing.yml, build.gradle, dockers/install/rpm/Dockerfile, dockers/install/upgrade-rpm/Dockerfile, scripts/install-test.sh
* Update to Java source compatibility
* Update install tests for java 11, also test 17, 21
=> RUN-3138: Use java 11

build.gradle
This change sets the values for the sonatype publish plugin
=> RUN-3329: sonatype url update
